"""
ui/themes.py — ShadowPort Scanner v2.3.0
Five built-in themes as Textual CSS variable sets.
"""

THEMES: dict[str, dict[str, str]] = {
    "cyber_green": {
        "--primary":    "#00ff88",
        "--secondary":  "#00cfff",
        "--accent":     "#00ff88",
        "--background": "#0a0e1a",
        "--surface":    "#111827",
        "--panel":      "#0d1929",
        "--border":     "#1e3a5f",
        "--text":       "#c9d1e0",
        "--dim":        "#607090",
        "--danger":     "#ff4455",
        "--warning":    "#ffcc00",
        "--success":    "#00ff88",
    },
    "blue_team": {
        "--primary":    "#4fc3f7",
        "--secondary":  "#81d4fa",
        "--accent":     "#0288d1",
        "--background": "#0d1b2a",
        "--surface":    "#1b2838",
        "--panel":      "#162030",
        "--border":     "#1e3a5f",
        "--text":       "#cfd8dc",
        "--dim":        "#546e7a",
        "--danger":     "#ef5350",
        "--warning":    "#ffa726",
        "--success":    "#66bb6a",
    },
    "purple_neon": {
        "--primary":    "#ce93d8",
        "--secondary":  "#f48fb1",
        "--accent":     "#ab47bc",
        "--background": "#0d0714",
        "--surface":    "#160d22",
        "--panel":      "#1a0f2e",
        "--border":     "#4a1f6e",
        "--text":       "#e1bee7",
        "--dim":        "#7b5f8a",
        "--danger":     "#ff4081",
        "--warning":    "#ffab40",
        "--success":    "#69f0ae",
    },
    "dark": {
        "--primary":    "#90caf9",
        "--secondary":  "#80cbc4",
        "--accent":     "#42a5f5",
        "--background": "#121212",
        "--surface":    "#1e1e1e",
        "--panel":      "#252525",
        "--border":     "#333333",
        "--text":       "#e0e0e0",
        "--dim":        "#757575",
        "--danger":     "#ef5350",
        "--warning":    "#ffa726",
        "--success":    "#66bb6a",
    },
    "light": {
        "--primary":    "#1565c0",
        "--secondary":  "#00838f",
        "--accent":     "#1976d2",
        "--background": "#f5f5f5",
        "--surface":    "#ffffff",
        "--panel":      "#e8eaf6",
        "--border":     "#c5cae9",
        "--text":       "#212121",
        "--dim":        "#757575",
        "--danger":     "#c62828",
        "--warning":    "#e65100",
        "--success":    "#2e7d32",
    },
}

THEME_LABELS = {
    "cyber_green": "Cyber Green",
    "blue_team":   "Blue Team",
    "purple_neon": "Purple Neon",
    "dark":        "Dark Mode",
    "light":       "Light Mode",
}
